info:
    dependencies:
        mokey: ${integrations.mokey.url}
        boober: ${integrations.boober.url}
        docker: ${integrations.docker-registry.url}
        unclematt: ${integrations.unclematt.url}
        cantus: ${integrations.cantus.url}

spring:
    profiles:
        active: local

integrations:
    mokey:
        url: http://mokey
    boober:
        url: http://boober
    unclematt:
        url: http://unclematt-aurora-daemons.utv.paas.skead.no
    cantus:
        url: http://cantus

gobo:
    graphql:
        tracing-enabled: false

aurora:
    starter:
        headerfilter:
            enabled: false

logging:
    level:
        no.skatteetaten: INFO
        org:
            jboss: WARN
            hibernate: WARN
            springframework: WARN
            apache: WARN
---
spring:
    profiles: local

integrations:
    boober:
        url: http://boober-aurora.utv.paas.skead.no
    mokey:
        url: http://mokey-aurora.utv.paas.skead.no
    cantus:
        url: http://cantus-aurora.utv.paas.skead.no
    docker-registry:
        url: https://test-docker-registry-internal-group.aurora.skead.no

management:
    server:
        port: 8081

openshift:
    cluster: utv
---
spring:
    profiles: openshift

aurora:
    token:
        location: /u01/secrets/app/aurora-token/token