mokey:
#    url: http://mokey-bas-paas-mokey.utv.paas.skead.no
    url: http://localhost:8082

boober:
    url: http://boober-aurora.utv.paas.skead.no

docker-registry:
    url: https://uil0paas-utv-registry01.skead.no:5000