info:
    dependencies:
        mokey: ${gobo.mokey.url}
        boober: ${gobo.boober.url}
        docker: ${gobo.docker-registry.url}
        unclematt: ${gobo.unclematt.url}

spring:
    profiles:
        active: local

gobo:
    mokey:
        url: http://mokey
    boober:
        url: http://boober
    unclematt:
        url: http://unclematt-aurora-daemons.utv.paas.skead.no
    cantus:
        url: http://localhost:8090
aurora:
    starter:
        headerfilter:
            enabled: false

logging:
    level:
        no.skatteetaten: INFO
        org:
            jboss: WARN
            hibernate: WARN
            springframework: WARN
            apache: WARN
---
spring:
    profiles: local

gobo:
    boober:
        url: http://boober-aurora.utv.paas.skead.no
    mokey:
        url: http://mokey-aurora.utv.paas.skead.no
    docker-registry:
        url: https://test-docker-registry-internal-group.aurora.skead.no
    cantus:
        url: http://localhost:8090

management:
    server:
        port: 8081

openshift:
    cluster: utv
---
spring:
    profiles: openshift