info:
    dependencies:
        mokey: ${gobo.mokey.url}
        boober: ${gobo.boober.url}
        docker: ${gobo.docker-registry.url}
        unclematt: ${gobo.unclematt.url}
        cantus: ${gobo.cantus.url}

spring:
    profiles:
        active: local

gobo:
    mokey:
        url: http://mokey
    boober:
        url: http://boober
    unclematt:
        url: http://unclematt-aurora-daemons.utv.paas.skead.no
    cantus:
        url: http://cantus

aurora:
    starter:
        headerfilter:
            enabled: false

logging:
    level:
        no.skatteetaten: INFO
        no.skatteetaten.aurora.gobo: DEBUG
        org:
            jboss: WARN
            hibernate: WARN
            springframework: WARN
            apache: WARN
---
spring:
    profiles: local

gobo:
    boober:
        url: http://boober-aurora.utv.paas.skead.no
    mokey:
        url: http://mokey-aurora.utv.paas.skead.no
    cantus:
        url: localhost:8090

management:
    server:
        port: 8081

---
spring:
    profiles: openshift