info:
    dependencies:
        mokey: ${integrations.mokey.url}
        boober: ${integrations.boober.url}
        docker: ${integrations.docker-registry.url}
        unclematt: ${integrations.unclematt.url}
        cantus: ${integrations.cantus.url}

spring:
    application:
        name: gobo
    profiles:
        active: local
    codec:
        max-in-memory-size: -1 # unlimited
    zipkin:
        enabled: false
    sleuth:
        enabled: false
    security:


graphql:
    packages: "no.skatteetaten.aurora.gobo.resolvers"

management:
    endpoints:
        web:
            exposure:
                include: info,health,prometheus,env,loggers

# https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/248
altair:
    static:
        basePath:

integrations:
    mokey:
        url: http://mokey
    boober:
        url: http://boober
    unclematt:
        url: http://unclematt-aurora-daemons.utv.paas.skead.no
    cantus:
        url: http://cantus
    docker:
        cluster:
            url: docker-registry.default.svc:5000
            https: false
            auth: Bearer
            readOnly: true
            enabled: true
        old:
            url: docker-registry.aurora.sits.no:5000
            guiUrlPattern: http://uil0paas-utv-registry01.skead.no:9090/tag/@group@/@name@/
            https: true
            auth: None
            readOnly: false
            enabled: true
        nexus-pull:
            url: container-registry-internal-private-pull.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: None
            readOnly: true
            enabled: true
        nexus-pull-public:
            url: container-registry-internal-public-pull.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: None
            readOnly: true
            enabled: true
        nexus-release:
            url: container-registry-internal-release.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: Basic
            readOnly: false

gobo:
    graphql:
        tracing-enabled: false

aurora.webflux.header.webclient.interceptor.enabled: true
aurora.mvc.header.filter.enabled: false
aurora.webflux.header.filter.enabled: false

logging:
    level:
        no.skatteetaten: DEBUG
        org:
            jboss: WARN
            hibernate: WARN
            springframework: WARN
            apache: WARN
---
spring:
    profiles: local

integrations:
    boober:
        url: http://boober.aurora.utv.paas.skead.no
    mokey:
        url: http://mokey-aurora.utv.paas.skead.no
    cantus:
        url: http://cantus.aurora.utv.paas.skead.no
    docker:
        cluster:
            url: docker-registry.default.svc:5000
            https: false
            auth: Bearer
            readOnly: true
            enabled: true
        old:
            url: docker-registry.aurora.sits.no:5000
            guiUrlPattern: http://uil0paas-utv-registry01.skead.no:9090/tag/@group@/@name@/
            https: true
            auth: None
            readOnly: false
            enabled: true
        nexus-pull:
            url: container-registry-internal-private-pull.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: None
            readOnly: true
            enabled: true
        nexus-pull-public:
            url: container-registry-internal-public-pull.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: None
            readOnly: true
            enabled: true
        nexus-release:
            url: container-registry-internal-release.aurora.skead.no:443
            guiUrlPattern: https://container-nexus.sits.no/#browse/search/docker=attributes.docker.imageName%3D@group@%2F@name@%20AND%20attributes.docker.imageTag%3D
            https: true
            auth: Basic
            readOnly: false


aurora.token.value: token

management:
    server:
        port: 8081

openshift:
    cluster: utv
---
spring:
    profiles: openshift

aurora:
    token:
        location: /u01/secrets/app/aurora-token/token