mokey:
    url: ${gobo.mokey.url:http://localhost:8082}

boober:
    url: http://boober-aurora.utv.paas.skead.no

docker-registry:
    url: https://uil0paas-utv-registry01.skead.no:5000

logging:
    level:
        no.skatteetaten.aurora.gobo: DEBUG
        org:
            springframework: WARN
            apache:
                catalina: WARN
                velocity: WARN
