kubernetes:
    url: https://utv-master.paas.skead.no:8443

spring:
    flyway:
        enabled: false

integrations:
    dbh:
        url: http://localhost:9090

gobo:
    graphqlUsage:
        fixedRate: 5000