CREATE TABLE FIELD (
   NAME         VARCHAR(200) CONSTRAINT PK_FIELD PRIMARY KEY,
   COUNT        INTEGER NOT NULL
);

CREATE TABLE FIELD_CLIENT (
    NAME        VARCHAR(200) CONSTRAINT PK_FIELD_CLIENT PRIMARY KEY,
    COUNT       INTEGER NOT NULL,
    FIELD_NAME  VARCHAR(200) NOT NULL REFERENCES FIELD(NAME)
);
