CREATE TABLE FIELD (
   ID       serial CONSTRAINT PK_FIELD PRIMARY KEY,
   NAME     VARCHAR(200) NOT NULL,
   COUNT    INTEGER NOT NULL
);

CREATE TABLE FIELD_CLIENT (
    ID       serial CONSTRAINT PK_FIELD_CLIENT PRIMARY KEY,
    FIELD_ID INTEGER NOT NULL REFERENCES FIELD(ID),
    NAME     VARCHAR(200) NOT NULL,
    COUNT    INTEGER NOT NULL
);